### ISSUE TITLE
Jest fails to import package

### ISSUE THREAD

**Issue by kajas90** [socure-inc/socure-docv-demo-app-react-native#12]
Hi!
I'm using v3 of docv react native wrapper. Everything works as expected except jest. We have discovered that your `main` path in `package.json` directs to `lib/commonjs/index` but you don't use commonJS anymore as there is no lib generated for this package. Can I ask you for fix or instructions what to do?

**Comment by kajas90** [comment]
I have also noticed that because you don't run commonJS types are not generated and we had to write our own types for the library

**Comment by buraksocure** [comment]
Thank you @kajas90 We will follow up with you through your email.

**Comment by buraksocure** [comment]
Hi @kajas90 This issue has been fixed within v3.1.3. Let us know if you need anything else.
